<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Database\ApplicationDbContext.cs" />
    <Compile Remove="Services\ReadOnlyDatabaseService.cs" />
    <Compile Remove="Database\AwsPostgresDbContext.cs" />
    <Compile Remove="Database\AwsPostgresReadOnlyDbContext.cs" />
    <Compile Remove="Services\ReadOnlyDatabaseService.cs" />
  </ItemGroup>

</Project>
